/// This is a autogenerated file by statemachine framework and should not be edited manually."

#include "ACStates.h"

/// Declare events.
enum EVENT
{
    EV_ON,
    EV_ERROR,
    EV_MONITOR_TEMP,
    EV_OK,
    EV_READY,
    EV_RUN,
    EV_MAINTAIN,
    EV_STOP,
    EV_STOPPED,
    EV_A_B,
};

class MotorMachine
{
public:
    int initialize(void);
    int start(void);
    int triggerEv(uint32_t ev, void* msg=NULL);
};
